# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up OCaml
      uses: avsm/setup-ocaml@v1.0.1
      with:
        ocaml-version: 4.08.1 # optional, default is 4.08.1

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Set up Coq
      run: |
        opam repo add coq-released https://coq.inria.fr/opam/released
        opam update -y
        opam install -y coq.8.11.1

    - name: Clone bug minimizer
      run: |
        git clone https://github.com/JasonGross/coq-tools.git
        sudo cp coq-tools/*.py /usr/bin/

    - name: Run minimizer
      run: ./run.sh
      timeout-minutes: 330 # Each job in a workflow can run for up to 6 hours of execution time, we want to make sure there's time to upload the files
    
    - run: cat bug.v
      if: always()

    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: bug.v
        path: bug.v
      if: always()

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        # name: # optional
        # A file, directory or wildcard pattern that describes what to upload
        path: .
      if: always()
